package com.o9paathshala.util;

import java.util.List;

import com.o9paathshala.dao.ConfiguredQuery;
import com.o9paathshala.dao.CreateQuerySQLConstants;

public class CreateQueries {

	public List<ConfiguredQuery> getQueries(List<ConfiguredQuery> cqList){
		List<ConfiguredQuery> cq=cqList;
		ConfiguredQuery cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.BATCH_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FACULTY_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FACULTY_SET_AUTOINCREMENT);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FACULTY_BATCH_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.STUDENT_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.STUDENT_SET_AUTOINCREMENT);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.SUBJECT_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TEST_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TEST_BATCH_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.SECTION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.MY_QUESTION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.RESULTS_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.SECTION_MY_QUESTION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.PURCHASED_QUESTION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.SECTION_PURCHASED_QUESTION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TEST_SECTION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FORUM_POST_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TAGS_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FORUM_POST_ANSWER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.POST_TAG_MAP);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.POST_LIKE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.POST_ANSWER_LIKE);
		cq.add(cqDTO);
		
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TEST_NOTIFICATION_TABLE);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FACULTY_TABLE_UPDATE_TRIGGER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FACULTY_TABLE_DELETE_TRIGGER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FACULTY_TABLE_INSERT_TRIGGER);
		cq.add(cqDTO); 
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.STUDENT_TABLE_DELETE_TRIGGER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.STUDENT_TABLE_INSERT_TRIGGER);
		cq.add(cqDTO);

		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.STUDENT_TABLE_UPDATE_TRIGGER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TEST_BATCH_INSERT_NOTIFY_TRIGGER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.TEST_UPDATE_NOTIFY_TRIGGER);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.RESULT_VIEW);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.PURCHASED_TEST_VIEW);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.MY_TEST_VIEW);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.FORUM_VIEW);
		cq.add(cqDTO);
		cqDTO=new ConfiguredQuery();
		cqDTO.setPsList(null);
		cqDTO.setQuery(CreateQuerySQLConstants.CREATE_EVENT);
		cq.add(cqDTO);
		return cq;
	}

}
